---
title: "Prioritizing Fire Hydrant Inspections in Philadelphia"
author: "Ran Xin, Ziqun Li, Leanne Chan"
date: "1/30/2020"
output:
  html_document#:
    code_folding: hide
    theme: united
    toc: yes
    toc_float: yes
    toc_depth: 5
  html_document:
    df_print: paged
    toc: yes
---

```{r setup, echo=TRUE, cache=TRUE, message=FALSE, warning=FALSE, results='hide'}
setwd("/Users/ranxin/Desktop/Practicum")

library(tigris)
options(tigris_use_cache = TRUE) 
library(tidycensus)
library(viridis)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
library(RSocrata)
library(gifski)
library(png)
library(ggsn)
library(gganimate)
library(tidyverse)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(knitr)
library(kableExtra)
library(car) #test colinarity
library(ggplot2)
library(dplyr)
library(gmodels)
library(MASS)
library(e1071)
library(Hmisc)
library(Boruta)
library(corrplot)
library(viridis)
library(stargazer)
library(tigris)
library(GoodmanKruskal)
library(spatstat)
library(riem)
library(readr)
library(readxl)
library(QuantPsyc)
library(lubridate)

##### SETUP #####
mapTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle=element_text(face="italic"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2)
  )
}

plotTheme <- function(base_size = 12) {
  theme(
    text = element_text( color = "black"),
    plot.title = element_text(size = 14,colour = "black"),
    plot.subtitle = element_text(face="italic"),
    plot.caption = element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line("grey80", size = 0.1),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=2),
    strip.background = element_rect(fill = "grey80", color = "white"),
    strip.text = element_text(size=12),
    axis.title = element_text(size=12),
    axis.text = element_text(size=10),
    plot.background = element_blank(),
    legend.background = element_blank(),
    legend.title = element_text(colour = "black", face = "italic"),
    legend.text = element_text(colour = "black", face = "italic"),
    strip.text.x = element_text(size = 14)
  )
}

#Nearest neighbor (NND) function
nn_function <- function(measureFrom,measureTo,k) {
  measureFrom_Matrix <-
    as.matrix(measureFrom)
  measureTo_Matrix <-
    as.matrix(measureTo)
  nn <-   
    get.knnx(measureTo, measureFrom, k)$nn.dist
  output <-
    as.data.frame(nn) %>%
    rownames_to_column(var = "thisPoint") %>%
    gather(points, point_distance, V1:ncol(.)) %>%
    arrange(as.numeric(thisPoint)) %>%
    group_by(thisPoint) %>%
    dplyr::summarize(pointDistance = mean(point_distance)) %>%
    arrange(as.numeric(thisPoint)) %>% 
    dplyr::select(-thisPoint) %>%
    pull()
  
  return(output)  
}

```

# Introduction

# Data

```{r data, echo=TRUE, cache=TRUE, message=FALSE, warning=FALSE, results='hide'}
##### DATA (external sources) #####
#load the boundary data
setwd("/Users/ranxin/Desktop/Practicum")
philly<- st_read("http://data.phl.opendata.arcgis.com/datasets/405ec3da942d4e20869d4e1449a2be48_0.geojson") %>%
  st_set_crs(4326) %>%
  na.omit() %>%
  st_transform(2272)

# load the neighborhood data
#neighbor <- 
  #st_read("data/Neighborhoods_Philadelphia/Neighborhoods_Philadelphia.shp")%>%
  #st_set_crs(4326) %>%
  #na.omit() %>%
  #st_transform(crs=2272)
# plot the neighbourhood
#ggplot() +
  #geom_sf(data=philly,fill=NA) +
  #geom_sf(data=neighbor,fill=NA) +
  #labs(title = "neighborhoods in Philly") +
  #mapTheme()

# load the census tracts data
tracts <- 
  st_read("http://data.phl.opendata.arcgis.com/datasets/ccdc0d022f4949a7b11333bd37231aef_0.geojson")%>%
  st_set_crs(4326) %>%
  na.omit() %>%
  st_transform(crs=2272)
# plot the census tracts
#ggplot() +
  #geom_sf(data=philly,fill=NA) +
  #geom_sf(data=tracts,fill=NA) +
  #labs(title = "Philadelphia census tracts") +
  #mapTheme()

#==================================================================
##### DATA (original) #####

# load the fire data
fire_excel<-read_excel('2015 to 2019 fires for u of pa report run 1620.xlsx')

fire.sf <- 
  fire_excel%>% 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326, agr = "constant") %>%
  st_set_crs(4326) %>%
  st_transform(2272)

fire.sf <- 
  st_intersection(fire.sf, philly)

#Plot all fire points (2015-2019)
#ggplot() +
  #geom_sf(data = philly, fill = "grey40") +
  #geom_sf(data = fire.sf , colour = "#FA7800", size = .75) +
  #labs(title = "Philly fires") +
  #mapTheme()

# load hydrant inspection data
inspect <- 
  st_read("PDF_Hydrant_Inspections_2019_for_MUSA/PDF_Hydrant_Inspections_2019.shp") %>%
  st_transform(crs=2272) 

# load the hydrant data
hydrants <- 
  st_read("Hydrants_2019/Hydrants_2019.shp") %>%
  st_transform(crs=2272) 

#ggplot() + 
  #geom_sf(data =hydrants, colour="#006699", size=0.3) +
  #geom_sf(data = philly,fill=NA) +
  #labs(title= "Hydrants in Philadelphia") +
  #mapTheme()

# load the engine locals data
engine_new <- 
  st_read("EngineLocals/EngineLocals_New.shp") %>%
  st_transform(crs=2272) 
#ggplot() + 
  #geom_sf(data =engine_new, colour="#006699", size=0.7) +
  #geom_sf(data = philly,fill=NA) +
  #labs(title= "Local engines (new)") +
  #mapTheme()

engine_old <- 
  st_read("EngineLocals/EngineLocals_Old.shp") %>%
  st_transform(crs=2272) 
#ggplot() + 
  #geom_sf(data =engine_old, colour="#006699", size=0.7) +
  #geom_sf(data = philly,fill=NA) +
  #labs(title= "Local engines (old)") +
  #mapTheme()
```

# Creating fishnets
800*800 fishnet
```{r fishnet, echo=TRUE, cache=TRUE, message=FALSE, warning=FALSE,fig.align='center'}
##### FISHNET#####
# Fire hydrants shall be provided for detached one- and two-family dwellings in accordance with both of the following: 
# (1) The maximum distance to a fire hydrant from the closest point on the building shall not exceed 600 ft (122183 m).
# (2) The maximum distance between fire hydrants shall not exceed 800 ft (244 m).
# create the 800ft grid cell fishnet
fishnet <- 
  st_make_grid(philly, cellsize = 800) %>%
  st_sf()
# clip the fishnet by the boundary
fishnet <- 
  fishnet[philly,] %>%
  mutate(uniqueID = rownames(.)) %>%
  dplyr::select(uniqueID)
# plot the fishnet
ggplot() +
  geom_sf(data=fishnet,fill=NA) +
  labs(title = "Philadelphia fishnet") +
  mapTheme()

# join fire data to the fishnet
fire_fishnet <- 
  fire.sf %>% 
  dplyr::select() %>% 
  mutate(count = 1) %>% 
  aggregate(., fishnet, sum) %>%
  mutate(count = ifelse(is.na(count), 0, count),
         uniqueID = rownames(.),
         cvID = sample(round(nrow(fishnet) / 24), size=nrow(fishnet), replace = TRUE))
#Map the fire fishnet map (2015-2019)
ggplot() +
  geom_sf(data = fire_fishnet, aes(fill = count)) +
  scale_fill_viridis(option = "A") +
  labs(title = "Count of fire incidents for the fishnet 2015-2019") +
  mapTheme()

# join hydrant data to the fishnet
hydrants_fishnet <- 
  hydrants %>% 
  dplyr::select() %>% 
  mutate(count = 1) %>% 
  aggregate(., fishnet, sum) %>%
  mutate(count = ifelse(is.na(count), 0, count),
         uniqueID = rownames(.),
         cvID = sample(round(nrow(fishnet) / 24), size=nrow(fishnet), replace = TRUE))
# map the hydrants fishnet map
ggplot() +
  geom_sf(data = hydrants_fishnet, aes(fill = count)) +
  scale_fill_viridis(option = "A") +
  labs(title = "Count of hydrants for the fishnet") +
  mapTheme()

```

